"""Update canonical_seed.csv with accurate per-item freshness_days (fridge shelf life)."""

import csv
import io
import pathlib

# Accurate refrigerator shelf life in days per canonical ingredient name.
# Sources: USDA FoodKeeper, FDA, general food safety guidelines.
FRESHNESS: dict[str, int] = {
    # ── PROTEIN ─────────────────────────────────────────────────────────────
    # Fresh raw poultry
    "chicken breast": 2,
    "chicken thigh": 2,
    "turkey breast": 2,
    "turkey tenderloin": 2,
    "ground turkey": 2,
    "chile limon chicken": 2,
    "cilantro lime chicken": 2,
    "hot italian turkey sausage": 2,
    "sweet italian chicken sausage": 2,
    "oven roasted chicken breast": 5,  # cooked deli
    "oven roasted turkey breast": 5,
    "honey roasted turkey breast": 5,
    "roasted turkey breast": 5,
    # Fresh raw beef/pork/lamb
    "ground beef": 2,
    "ground pork": 2,
    "ground lamb": 2,
    "ground bison": 2,
    "ground beef patty": 2,
    "wagyu beef patty": 2,
    "stew meat": 2,
    "pork chorizo": 2,
    "sausage": 2,
    "sweet italian pork sausage": 2,
    "pork tenderloin": 3,
    "pork chop": 3,
    "pork loin roast": 3,
    "pork carnitas": 4,  # cooked
    "beef sirloin": 3,
    "beef tenderloin": 3,
    "steak": 3,
    "brisket": 3,
    "short ribs": 3,
    "beefsteak": 3,
    "ny strip steak": 3,
    "ribeye steak": 3,
    "sirloin tip": 3,
    "wagyu filet mignon": 3,
    "wagyu ribeye": 3,
    "wagyu strip steak": 3,
    "lamb chop": 3,
    # Deli/cured meats
    "bacon": 7,
    "applewood bacon": 7,
    "turkey bacon": 7,
    "ham": 5,
    "honey ham": 5,
    "genoa salami": 7,
    "prosciutto": 5,
    "uncured pepperoni": 14,
    # Cooked/processed protein
    "beef meatballs": 4,
    "breaded chicken nuggets": 4,
    "broccoli & cheddar quiche": 5,
    "crab cake": 3,
    "falafel": 5,
    # Fresh seafood
    "salmon fillet": 2,
    "sockeye salmon": 2,
    "steelhead trout": 2,
    "tilapia": 2,
    "cod fillet": 2,
    "shrimp": 2,
    "scallops": 2,
    "crab": 2,
    "halibut": 2,
    "mahi mahi": 2,
    "tuna": 2,
    "clams": 2,
    "mussels": 2,
    "catfish": 2,
    "trout": 2,
    "lobster": 1,
    "oysters": 5,
    # Smoked/cured seafood
    "smoked salmon": 14,
    "smoked ahi tuna": 5,
    # Canned seafood (unopened shelf-stable)
    "sardines": 730,
    "anchovies": 730,
    # Eggs & egg products
    "egg": 35,
    "egg white": 4,
    # Plant-based protein
    "tofu": 5,
    "tempeh": 7,
    "seitan": 5,
    "edamame": 5,
    # ── VEGETABLE ───────────────────────────────────────────────────────────
    # Leafy greens (most perishable)
    "spinach": 5,
    "arugula": 5,
    "mixed greens": 5,
    "swiss chard": 5,
    "collard greens": 5,
    "watercress": 3,
    "superblend salad": 5,
    "green kale": 7,
    "kale": 7,
    "romaine lettuce": 7,
    "iceberg lettuce": 7,
    "green leaf lettuce": 7,
    "classic caesar salad kit": 5,
    # Brassicas
    "broccoli": 5,
    "cauliflower": 7,
    "brussels sprouts": 7,
    "cabbage": 14,
    "red cabbage": 14,
    "bok choy": 5,
    "riced cauliflower": 7,
    "cauliflower linguine": 5,
    # Fruiting vegetables
    "bell pepper": 10,
    "tomato": 7,
    "cherry tomato": 7,
    "cucumber": 7,
    "zucchini": 7,
    "eggplant": 7,
    "poblano pepper": 7,
    "jalapeno": 14,
    "serrano pepper": 14,
    "corn": 3,
    # Alliums
    "onion": 30,
    "red onion": 30,
    "garlic": 30,
    "shallot": 30,
    "scallion": 7,
    "leek": 14,
    # Root vegetables
    "carrot": 21,
    "rainbow baby carrot": 14,
    "beet": 21,
    "radish": 14,
    "turnip": 14,
    "parsnip": 21,
    "celery": 14,
    "fennel": 7,
    "fingerling potato": 21,
    "red potato": 21,
    "yellow potato": 21,
    "potato": 30,
    "sweet potato": 30,
    # Squash
    "butternut squash": 90,
    "acorn squash": 90,
    "spaghetti squash": 90,
    # Pods & legume-veg
    "asparagus": 4,
    "green bean": 7,
    "pea": 5,
    "snap pea": 5,
    "snow pea": 5,
    "french onion green bean": 7,
    # Fungi
    "mushroom": 7,
    "portobello mushroom": 7,
    "shiitake mushroom": 7,
    "baby bella mushroom": 7,
    # Misc veg
    "artichoke": 7,
    "black olives": 7,
    "green olives": 7,
    "sauerkraut": 90,
    "black-eyed peas": 365,
    # ── FRUIT ───────────────────────────────────────────────────────────────
    # Citrus (long-lasting)
    "orange": 21,
    "lemon": 21,
    "lime": 21,
    "grapefruit": 21,
    # Apples & pears (long-lasting refrigerated)
    "apple": 30,
    "envy apple": 30,
    "honeycrisp apple": 30,
    "pink lady apple": 30,
    "pear": 7,
    # Berries (most perishable)
    "strawberry": 5,
    "blueberry": 10,
    "raspberry": 3,
    "blackberry": 3,
    "cherry": 5,
    # Tropical
    "banana": 5,
    "mango": 5,
    "pineapple": 7,
    "papaya": 5,
    "guava": 5,
    "kiwi": 14,
    "passion fruit": 7,
    "coconut": 7,
    # Melons
    "watermelon": 7,
    "cantaloupe": 5,
    "honeydew": 5,
    # Stone fruit
    "peach": 5,
    "plum": 5,
    # Other fresh fruit
    "grape": 14,
    "seedless green grape": 14,
    "seedless red grape": 14,
    "avocado": 4,
    "pomegranate": 14,
    "fig": 3,
    # Dried fruit (shelf-stable)
    "date": 180,
    "raisins": 180,
    "dried cranberries": 180,
    "dried apricots": 180,
    "apple chips": 180,
    # ── DAIRY ───────────────────────────────────────────────────────────────
    "whole milk": 7,
    "skim milk": 7,
    "heavy cream": 14,
    "half and half": 14,
    "butter": 30,
    "cream cheese": 14,
    "cream cheese spread": 14,
    "dairy-free cream cheese": 14,
    "sour cream": 21,
    "dairy-free sour cream": 14,
    "plain yogurt": 21,
    "greek yogurt": 21,
    "cottage cheese": 14,
    "ricotta cheese": 7,
    "mozzarella cheese": 14,
    "mozzarella ball": 7,
    "mozzarella string cheese": 21,
    "cheddar cheese": 30,
    "parmesan cheese": 30,
    "feta cheese": 14,
    "goat cheese": 14,
    "swiss cheese": 21,
    "monterey jack cheese": 21,
    "brie": 14,
    "blue cheese": 14,
    "gruyere cheese": 30,
    "havarti cheese slice": 14,
    "italian cheese blend": 21,
    "mexican blend cheese": 21,
    "yellow american cheese slice": 14,
    "creme fraiche": 14,
    "creme de brie cheese": 14,
    "cotija cheese": 21,
    "gouda cheese": 21,
    # ── GRAIN ───────────────────────────────────────────────────────────────
    # Dry grains (pantry-stable)
    "white rice": 365,
    "brown rice": 180,
    "quinoa": 365,
    "rolled oats": 365,
    "steel cut oats": 365,
    "farro": 365,
    "barley": 365,
    "bulgur wheat": 365,
    "couscous": 365,
    "polenta": 365,
    "cornmeal": 365,
    "millet": 365,
    "amaranth": 365,
    "buckwheat": 365,
    "teff": 365,
    "spelt": 365,
    # Dry pasta
    "pasta": 365,
    "whole wheat pasta": 365,
    "egg noodles": 365,
    "rice noodles": 365,
    "chiocciole pasta": 365,
    "fettuccine pasta": 365,
    "linguine pasta": 365,
    "orzo": 365,
    "raviolini pasta": 5,  # fresh refrigerated
    "rigati pasta": 365,
    # Fresh/refrigerated pasta & dough
    "four cheese mini ravioli": 5,
    "four cheese tortelloni": 5,
    "gnocchi": 5,
    "udon noodles": 5,
    "yakisoba noodles": 5,
    "pizza dough": 3,
    "cilantro lime white rice": 5,  # cooked
    "crescent rolls": 7,
    # Flour
    "all purpose flour": 365,
    "whole wheat flour": 180,
    "bread flour": 365,
    "rice flour": 365,
    "almond flour": 90,
    # Bread & rolls
    "whole wheat bread": 7,
    "white bread": 7,
    "sourdough bread": 7,
    "honey wheat bread": 7,
    "flour tortilla": 7,
    "corn tortilla": 7,
    "corn + wheat tortilla": 7,
    "hamburger bun": 7,
    "brioche burger bun": 5,
    "brioche hot dog bun": 5,
    "wheat hot dog bun": 7,
    "naan": 5,
    "pita": 5,
    "plain bagel": 5,
    "everything bagel": 5,
    "ciabatta roll": 3,
    "demi-baguette": 3,
    "croissants": 3,
    # Misc grain
    "panko breadcrumbs": 180,
    "breadcrumbs": 180,
    "granola": 90,
    "popcorn": 90,
    "croutons": 90,
    "cornstarch": 730,
    # ── LEGUME ──────────────────────────────────────────────────────────────
    # Dried beans (very shelf-stable)
    "black beans": 365,
    "chickpeas": 365,
    "lentils": 365,
    "kidney beans": 365,
    "pinto beans": 365,
    "navy beans": 365,
    "split peas": 365,
    "lima beans": 365,
    "fava beans": 365,
    "mung beans": 365,
    "adzuki beans": 365,
    "soybeans": 365,
    # Prepared legume products
    "hummus": 7,
    "french onion hummus": 7,
    "refried red beans": 4,
    "peanut butter": 90,
    "peanuts": 90,
    # ── NUT ─────────────────────────────────────────────────────────────────
    "almonds": 180,
    "cashews": 180,
    "pistachios": 180,
    "walnuts": 90,
    "pecans": 90,
    "hazelnuts": 90,
    "macadamia nuts": 90,
    "pine nuts": 90,
    "brazil nuts": 90,
    "almond butter": 90,
    "cashew butter": 90,
    # ── SEED ────────────────────────────────────────────────────────────────
    "chia seeds": 365,
    "flaxseeds": 365,
    "sesame seeds": 365,
    "poppy seeds": 365,
    "hemp seeds": 180,
    "sunflower seeds": 180,
    "pumpkin seeds": 180,
    "tahini": 90,
    # ── FAT ─────────────────────────────────────────────────────────────────
    "olive oil": 60,
    "sesame oil": 60,
    "vegetable oil": 90,
    "avocado oil": 90,
    "ghee": 90,
    "lard": 90,
    "coconut oil": 180,
    "mayonnaise": 60,
    "ranch dressing": 60,
    "caesar dressing": 60,
    "vinaigrette": 60,
    "asiago peppercorn dressing": 60,
    "avocado spread": 2,
    "pesto aioli": 7,
    # ── HERB (fresh) ────────────────────────────────────────────────────────
    "basil": 7,
    "cilantro": 7,
    "mint": 7,
    "chives": 7,
    "dill": 7,
    "tarragon": 7,
    "oregano": 7,
    "bay leaf": 7,
    "sage": 10,
    "parsley": 10,
    "thyme": 10,
    "rosemary": 14,
    "lemongrass": 14,
    "fresh turmeric": 14,
    "fresh ginger": 21,
    # ── SPICE (dried) ───────────────────────────────────────────────────────
    # Ground spices: ~2 years; whole spices: ~3 years
    "salt": 1825,
    "black pepper": 730,
    "cumin": 730,
    "paprika": 730,
    "chili powder": 730,
    "garlic powder": 730,
    "onion powder": 730,
    "cayenne pepper": 730,
    "cinnamon": 730,
    "nutmeg": 730,
    "ground ginger": 730,
    "turmeric powder": 730,
    "coriander powder": 730,
    "cardamom": 730,
    "cloves": 730,
    "allspice": 730,
    "dried oregano": 730,
    "dried thyme": 730,
    "dried basil": 730,
    "dried rosemary": 730,
    "dried bay leaves": 1095,
    "red pepper flakes": 730,
    "fennel seeds": 1095,
    "mustard powder": 730,
    "curry powder": 730,
    "garam masala": 730,
    "italian seasoning": 730,
    "Old Bay seasoning": 730,
    "everything bagel seasoning": 365,
    "balsamic seasoning": 730,
    "blackening seasoning": 730,
    "chorizo spice blend": 730,
    "fajita spice blend": 730,
    "garlic and herb seasoning": 730,
    "herbs de provence": 730,
    "chipotle powder": 730,
    "cajun spice blend": 730,
    "mediterranean spice blend": 730,
    "ranch seasoning": 365,
    "southwest spice blend": 730,
    "tandoori spice blend": 730,
    "tuscan heat spice": 730,
    "za'atar seasoning": 730,
    "zingy pepper & garlic seasoning": 730,
    "saffron": 730,
    # ── CONDIMENT ───────────────────────────────────────────────────────────
    # Vinegars (essentially indefinite shelf life)
    "apple cider vinegar": 365,
    "white wine vinegar": 365,
    "red wine vinegar": 365,
    "balsamic vinegar": 365,
    "rice wine vinegar": 365,
    "sherry vinegar": 365,
    # Sweeteners (very shelf-stable)
    "honey": 1825,
    "maple syrup": 365,
    "agave nectar": 365,
    # Sauces with long shelf life (opened, refrigerated)
    "soy sauce": 180,
    "hot sauce": 180,
    "sriracha": 180,
    "ketchup": 180,
    "yellow mustard": 180,
    "dijon mustard": 180,
    "honey mustard": 90,
    "worcestershire sauce": 365,
    "fish sauce": 365,
    "buffalo sauce": 60,
    "bbq sauce": 60,
    "teriyaki sauce": 60,
    "sweet teriyaki": 60,
    "sesame ginger": 60,
    "bulgogi sauce": 60,
    "coconut aminos": 90,
    "pickled red onion": 30,
    "apricot jam": 90,
    "cranberry jam": 90,
    # Sauces that need quick use (opened)
    "oyster sauce": 90,
    "hoisin sauce": 90,
    "miso paste": 90,
    "thai peanut sauce": 14,
    "tzatziki sauce": 7,
    "pesto": 7,
    "kale spinach pesto": 7,
    "guacamole": 3,
    "salsa": 7,
    "mild fresh salsa": 7,
    "pico de gallo salsa": 5,
    "tomato sauce": 7,
    "marinara": 7,
    "classic alfredo sauce": 7,
    "creamy vodka sauce": 7,
    "creamy cheddar sauce": 7,
    "coconut curry sauce": 7,
    "saag sauce": 7,
    "red enchilada sauce": 7,
    "adobo sauce": 14,
    "beef demi-glace": 14,
    # Short-life pantry items
    "tomato paste": 7,
    "canned tomatoes": 5,
    "coconut milk": 5,
    "chicken broth": 5,
    "vegetable broth": 5,
    "beef broth": 5,
    # ── BAKING ──────────────────────────────────────────────────────────────
    # Sugars (extremely shelf-stable)
    "granulated sugar": 730,
    "brown sugar": 730,
    "powdered sugar": 730,
    "coconut sugar": 730,
    # Dry leaveners & starches
    "baking powder": 365,
    "baking soda": 365,
    "active dry yeast": 120,
    "cream of tartar": 730,
    "arrowroot powder": 730,
    "gelatin": 730,
    # Flavorings
    "vanilla extract": 1825,
    "molasses": 365,
    # Chocolate
    "cocoa powder": 730,
    "chocolate chips": 365,
    "dark chocolate": 365,
    "milk chocolate": 365,
    "white chocolate": 365,
    "sprinkles": 730,
    # Perishable baked goods
    "blueberry muffin": 3,
    "cookie dough": 7,
    # ── BEVERAGE ────────────────────────────────────────────────────────────
    "coffee": 30,
    "tea": 365,
    "orange juice": 7,
    "apple juice": 7,
    "lemon juice": 14,
    "lime juice": 14,
    "almond milk": 7,
    "oat milk": 7,
    "soy milk": 7,
    "coconut water": 3,
    "bone broth": 5,
    "kombucha": 30,
    "red wine": 5,
    "white wine": 5,
    "water": 3650,
}

# Category-level defaults for anything not individually listed
CATEGORY_DEFAULTS: dict[str, int] = {
    "protein": 4,
    "vegetable": 7,
    "fruit": 7,
    "dairy": 14,
    "grain": 180,
    "legume": 365,
    "nut": 180,
    "seed": 365,
    "fat": 30,
    "herb": 7,
    "spice": 365,
    "condiment": 30,
    "baking": 365,
    "beverage": 7,
}

src = (
    pathlib.Path(__file__).parent.parent
    / "src"
    / "pantry_cooking_vibes"
    / "_assets"
    / "canonical_seed.csv"
)
rows = list(csv.DictReader(io.StringIO(src.read_text(encoding="utf-8"))))

out = io.StringIO()
w = csv.DictWriter(
    out,
    fieldnames=["name", "category", "default_unit", "aliases", "freshness_days"],
    lineterminator="\n",
)
w.writeheader()

unlisted = []
for r in rows:
    name = r["name"].strip()
    cat = r.get("category", "").strip()
    if name in FRESHNESS:
        fd = FRESHNESS[name]
    else:
        fd = CATEGORY_DEFAULTS.get(cat, "")
        unlisted.append(name)
    r["freshness_days"] = fd
    w.writerow(r)

src.write_text(out.getvalue(), encoding="utf-8")
print(f"Updated {len(rows)} rows.")
if unlisted:
    print(f"Used category default for {len(unlisted)} unlisted items:")
    for n in unlisted:
        print(f"  {n}")
